WSPlus.WEB/Models/ErrorViewModel.cs
namespace WSPlus.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WSPlus.WEB/Controllers/AtendenteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Text;
using WSPlus.DATA.Models;
using WSPlus.DATA.Services;

namespace WSPlus.WEB.Controllers
{
    public class AtendenteController : Controller
    {
        private  AtendenteService oAtendenteService = new AtendenteService();
        public IActionResult Index()
        {
            List<Atendente> oListAtendente = oAtendenteService.oRepositoryAtendente.SelecionarTodos();
            return View(oListAtendente);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Atendente model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            oAtendenteService.oRepositoryAtendente.Incluir(model);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Atendente oAtendente = oAtendenteService.oRepositoryAtendente.SelecionarPk(id);
            return View(oAtendente);
        }

        public IActionResult Edit(int id)
        {
            Atendente oAtendente = oAtendenteService.oRepositoryAtendente.SelecionarPk(id);
            return View(oAtendente);
        }
    }
}

WSPlus.WEB/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Text;
using WSPlus.DATA.Models;
using WSPlus.DATA.Services;

namespace WSPlus.WEB.Controllers
{
    public class EmpresaController : Controller
    {
        private EmpresaService oEmpresaService = new EmpresaService();
        public IActionResult Index()
        {
            List<Empresa> oListEmpresa = oEmpresaService.oRepositoryEmpresa.SelecionarTodos();
            return View(oListEmpresa);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Empresa model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            oEmpresaService.oRepositoryEmpresa.Incluir(model);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Empresa oListEmpresa = oEmpresaService.oRepositoryEmpresa.SelecionarPk(id);
            return View(oListEmpresa);
        }

        public IActionResult Edit(int id)
        {
           Empresa oListEmpresa = oEmpresaService.oRepositoryEmpresa.SelecionarPk(id);
            return View(oListEmpresa);
        }
    }
}

WSPlus.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WSPlus.WEB.Models;

namespace WSPlus.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WSPlus.WEB/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace WSPlus.WEB.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WSPlus.WEB/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using WSPlus.DATA.Models;
using WSPlus.DATA.Services;
namespace WSPlus.WEB.Controllers
{
    
    public class UsuarioController : Controller
    {
        private UsuarioService oUsuarioService = new UsuarioService();
        public IActionResult Index()
        {
            List<Usuario>oListUsuario = oUsuarioService.oRepositoryUsuario.SelecionarTodos();
            return View(oListUsuario);
        }

        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        public IActionResult Create(Usuario model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            oUsuarioService.oRepositoryUsuario.Incluir(model);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Usuario oUsuario=oUsuarioService.oRepositoryUsuario.SelecionarPk(id);
            return View(oUsuario);
        }

        public IActionResult Edit (int id)
        {
            Usuario oUsuario = oUsuarioService.oRepositoryUsuario.SelecionarPk(id);
            return View(oUsuario);
        }
        [HttpPost]
        public IActionResult Edit(Usuario model)
        {
            Usuario oUsuario = oUsuarioService.oRepositoryUsuario.Alterar(model);

            int id = oUsuario.Id;

            return RedirectToAction("Details", new { id });
        }
        public IActionResult Delete(int id)
        {
            oUsuarioService.oRepositoryUsuario.Excluir(id);
            return RedirectToAction("index");
        }

    }
}

WSPlus.WEB/Views/Atendente/Create.cshtml
@model WSPlus.DATA.Models.Atendente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Atendente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WSPlus.WEB/Views/Atendente/Details.cshtml
@model WSPlus.DATA.Models.Atendente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Atendente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WSPlus.WEB/Views/Atendente/Edit.cshtml
@model WSPlus.DATA.Models.Atendente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Atendente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WSPlus.WEB/Views/Atendente/Index.cshtml
@model IEnumerable<WSPlus.DATA.Models.Atendente>

@{
    ViewData["Title"] = "Atendente";
}

<h1>Atendente</h1>

<p>
    <a class="btn btn-outline-success " asp-action="Create">Novo Atendente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>

                <td>
                    <a asp-action="Edit" class="btn btn-outline-success  " asp-route-id="@item.Id">Alterar</a>
                    <a asp-action="Details" class="btn btn-outline-primary " asp-route-id="@item.Id">Detalhes</a>
                    <a asp-action="Delete" class="btn btn-outline-danger " asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WSPlus.WEB/Views/Empresa/Details.cshtml
@model WSPlus.DATA.Models.Empresa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeFantasia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeFantasia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RazaoSocial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CnaeFiscal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CnaeFiscal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cnpj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cnpj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InscricaoEstadual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InscricaoEstadual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InscricaoMunicipal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InscricaoMunicipal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WSPlus.WEB/Views/Empresa/Index.cshtml
@model IEnumerable<WSPlus.DATA.Models.Empresa>

@{
    ViewData["Title"] = "Empresa";
}

<h1>Empresa</h1>

<p>
    <a class="btn btn-outline-success " asp-action="Create">Nova Empresa</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeFantasia)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeFantasia)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
                    
            </td>
           
            <td>
               <a asp-action="Edit" class="btn btn-outline-success " asp-route-id="@item.Id">Alterar</a> 
               <a asp-action="Details" class="btn btn-outline-primary " asp-route-id="@item.Id">Detalhes</a> 
               <a asp-action="Delete" class="btn btn-outline-danger " asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

WSPlus.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

WSPlus.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - WSPlus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WSPlus.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-controller="Cliente" asp-action="Index">WSPlus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresa" asp-action="Index">Empresa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Atendente" asp-action="Index">Atendente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WSPlus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WSPlus.WEB/Views/Usuario/Create.cshtml
@model WSPlus.DATA.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Usuario</h4>
<hr />
<div>
    <a class="btn btn-outline-primary m-1" asp-action="Index">Voltar</a>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAtendente" class="control-label"></label>
                <input asp-for="IdAtendente" class="form-control" />
                <span asp-validation-for="IdAtendente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="nome" class="control-label">Perfil</label>                
                <select asp-for="IdPerfil" class="form-control">
                <option value="0">Selecione</option>
                <option value="Admin">Administrador</option>
                <option value="Padrao">Padrão</option>
                <option value="Limitado">Limitado</option>
                </select>
            </div>
            <div class="form-group">
               <input type="submit" value="Salvar" class="btn btn-outline-success m-1" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WSPlus.WEB/Views/Usuario/Details.cshtml
@model WSPlus.DATA.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <div>
        <a asp-action="Edit" class="btn btn-outline-success m-1" asp-route-id="@Model?.Id">Editar</a>
        <a class="btn btn-outline-primary m-1" asp-action="Index">Voltar</a>
    </div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescricaoPerfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescricaoPerfil)
        </dd>
        
        
    </dl>
</div>

WSPlus.WEB/Views/Usuario/Edit.cshtml
@model WSPlus.DATA.Models.Usuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Alterar dados do Usuario</h1>

<h4>Usuario</h4>
<hr />
<div>
    <a class="btn btn-outline-primary m-1" asp-action="Index">Voltar</a>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAtendente" class="control-label"></label>
                <input asp-for="IdAtendente" class="form-control" />
                <span asp-validation-for="IdAtendente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="nome" class="control-label">Perfil</label>
                <select asp-for="DescricaoPerfil" class="form-control">
                    <option value="0">Selecione</option>
                    <option value="Admin">Administrador</option>
                    <option value="Padrao">Padrão</option>
                    <option value="Limitado">Limitado</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success m-1" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WSPlus.WEB/Views/Usuario/Index.cshtml
@model IEnumerable<WSPlus.DATA.Models.Usuario>

@{
    ViewData["Title"] = "Usuários";
}

<h1>Usuários</h1>

<p>
    <a class="btn btn-outline-success " asp-action="Create">Novo Usuário</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            
            <td>
                    <a asp-action="Edit" class="btn btn-outline-success " asp-route-id="@item.Id">Alterar</a> 
                    <a asp-action="Details" class="btn btn-outline-primary " asp-route-id="@item.Id">Detalhes</a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-outline-danger m-1" data-bs-toggle="modal" data-bs-target="#DeleteModal-@item.Id">
                        <i = class="fa fa-trash"> Deletar </i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="DeleteModal-@item.Id" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="DeleteModalLabel">Excluir Cliente</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.Nome?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-secondary m-1" data-bs-dismiss="modal">Não</button>
                                    <a asp-action="Delete" class="btn btn-outline-danger m-1" asp-route-id="@item.Id">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>

            </td>
        </tr>
}
    </tbody>
</table>